public class Main {

    public static void main(String[] args) {

        Livro l1 = new Livro("Clean Code", "978-0132350884");
        Livro l2 = new Livro("Clean Code", "978-0132350884");
        System.out.println(l1 == l2); // ?
        System.out.println(l1.equals(l2)); // ?
    }
}
// L1 E L2 SÃO OBJETOS DIFERENTES, MESMO CONTEUDO, POR ISSO O RESULTADO DO == É FALSE, POIS ELE COMPARA AS REFERENCIAS DE MEMORIA, ENQUANTO O EQUALS COMPARA O CONTEUDO DOS OBJETOS, SE O EQUALS NAO FOR SOBRESCRITO NA CLASSE LIVRO, ELE VAI HERDAR O COMPORTAMENTO DA CLASSE OBJECT, QUE TAMBEM COMPARA AS REFERENCIAS DE MEMORIA, ENTÃO O RESULTADO DO EQUALS TAMBEM VAI SER FALSE.